### ISSUE TITLE
Sorting increments by 10 ?

### ISSUE THREAD

**Issue by Faagerholm** [matthiask/django-admin-ordering#14]
Hi, I have been reading your code and have a question regarding the implementation of updating the order in JS. Is there a reason why you increment the order by 10? I wasted a few hours wondering why my code had this strange. Wouldn't it be enough incrementing the order by 1?

If you are still maintaining this project a small guide would be useful so new developers wouldn't stumble upon the same problem. 

**Problem**
Editing the order in the django admin panel increments the value by 10 resulting in a feature we didn't expect. 

```python
function updateOrdering(nodes) {
        var incOrdering = 10;
        var maxOrdering = nodes.length * incOrdering;
        nodes.each(function(index) {
          var row = $(this);
          var rowOrdering = data.fieldDesc
            ? maxOrdering - incOrdering * index
            : incOrdering * (index + 1);
          row.find(inputFieldSelector).val(rowOrdering);
          row.removeClass("row1 row2").addClass(index % 2 ? "row2" : "row1");
        });
      }
```
[This line](https://github.com/matthiask/django-admin-ordering/blob/master/admin_ordering/static/admin_ordering/admin_ordering.js#L51)

**Comment by matthiask** [comment]
Hey, that's a good question, and there is a historical reason for this. 

FeinCMS's ItemEditor used increments of one which lead some developers to believe that the ordering field can also be used as an index. This lead to crashes as soon as elements were removed in-between without renumbering the remaining elements.

The replacement, [django-content-editor](https://github.com/matthiask/django-content-editor), was changed to use increments of 10 to make it obvious that the ordering value does not have any meaning apart from giving relative ordering to elements.

django-admin-ordering inherits this behavior.

Apart from the historical reason, sometimes it's useful to assign e.g. a value of 25 to add an element in-between quickly. But that's not the main reason for this behavior.

**Comment by fabiocaccamo** [comment]
Another reason is: You can’t insert programmatically a new object between 2 existing objects if ordering values are sequential.

**Comment by Faagerholm** [comment]
Thank you for your reply. I do understand both reasons for this decision. We will just have to mind this in our code.
