### ISSUE TITLE
not able to reorder on mobile/tablet devices

### ISSUE THREAD

**Issue by etacticsgroup** [matthiask/django-admin-ordering#19]

**Comment by etacticsgroup** [comment]
Hello! Not sure if there is a quick fix for this, works perfectly on desktop/laptop but when it's on mobile or tablet i am not able to click the element to drag.

**Comment by matthiask** [comment]
We're bundling a prehistoric version of jQuery UI for the draggable behavior (1.11.4, from 2015). Maybe a newer version would work?

**Comment by matthiask** [comment]
I think this is improved by #26
