### ISSUE TITLE
Inlines ordering is not updated on page load.

### ISSUE THREAD

**Issue by fabiocaccamo** [matthiask/django-admin-ordering#22]
This issue happens only when this library is added to an existing model with an order field and the values are sequential (1, 2, 3, ...) without "free" space in between.

In my case, the problem is that I need to insert new items between existing ones, and I need to use an intermediate order value for ensuring the ordering.

Since the field already exists, the order value is not updated until some re-ordering through the UI.

This problem could be easily fixes by calling `updateOrdering` on page load.

**Comment by fabiocaccamo** [comment]
@matthiask thank you!

**Comment by matthiask** [comment]
You're welcome!
