### ISSUE TITLE
Up and down arrows as alternative control?

### ISSUE THREAD

**Issue by foucdeg** [matthiask/django-admin-ordering#25]
Hi again, 

Our StackedInline rows are quite tall as you can see in the screenshot below.
This means that reordering by drag and drop can get difficult because the distance to cover is sometimes more than the available vertical space on laptop screens.

A possible solution woud be to add optional up and down arrow buttons, next to the dragging button, that move the block one notch up and down.

Is this a feature you'd consider? I could try to make the PR.

<img width="684" alt="image" src="https://github.com/user-attachments/assets/adf2fd06-6541-4e72-b24b-03bff1257fed">

**Comment by matthiask** [comment]
Yes, I think this might be a good addition. Drag'n'drop interfaces aren't accessible to everyone!

Automatically scrolling the content if the mouse reaches the edges of the viewport could also be a good idea for something like this. I implemented that [here](https://github.com/feincms/django-content-editor/commit/714ff5cf91af917ba98c67b6d0616db061b43288), for a different project which you might also be interested in, judging from the way your blocs look: https://django-content-editor.readthedocs.io/en/latest/

**Comment by foucdeg** [comment]
Both good solutions, and the other project as well could be interesting, adding a rich text editor is definitely on our roadmap.
I can try to write a PR with opt-in scroll behaviour and up/down buttons early next week.

**Comment by matthiask** [comment]
closed by #26
