### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by fabiocaccamo** [matthiask/django-admin-ordering#3]
I just tried this app and it is good, by the way I think it could be improved a lot, so I give you some ideas:

1.  When dragging a row it would be better to leave a ghost of the row, check [this](https://bevacqua.github.io/dragula/) - #5 (not exactly the same)
2. I added your app to an existing project where the ordering field is a **priority** field (the order is descending). It would be nice to support a reversed order like: `ordering_field = '-order'`- #4 
3. Possibilty to display a draggable handle with drag cursor - #5
4. Possibilty to display a _move-up_/_move-down_ control as `list_display` item
5. Automatically add the `ordering_field` to `list_display` and `list_editable`
6. Possibility to hide the `ordering_field` - #5
7. Placeholder height should be dynamic and equal to the dragged row height (if you want to test this issue just add an image preview column) - #4

**Comment by matthiask** [comment]
I think I do not agree with 5. We shouldn't do this. We *could* add a few system checks to ensure that users have configured django-admin-ordering correctly but we shouldn't automatically modify `list_display`/`list_editable`.

Everything else has been done, thank you very much!
