### ISSUE TITLE
ManyToMany field ordering

### ISSUE THREAD

**Issue by mprakasht** [matthiask/django-admin-ordering#9]
ManyToMany admin.TabularInline to display related objects in the admin app, and it works great except I can't figure out what to set the "ordering" property to so it can sort by one of the cross-referenced field names. I used this module django-admin-ordering==0.9.0.

**Comment by matthiask** [comment]
I'm not sure I understand. Can you show the admin code and explain what you are trying to do in a more concrete way?

**Comment by matthiask** [comment]
Please provide additional details and reopen.
